M48
; DRILL file {KiCad 8.0.4} date 2024-08-27T21:02:41+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-27T21:02:41+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X86.75Y-132.12
X113.25Y-132.12
T2
X77.5Y-77.5
X77.5Y-122.5
X122.5Y-77.5
X122.5Y-122.5
M30
