//
// Created by nico on 16.07.24.
//

#ifndef INC_3_INTER_INTEGRATED_CIRCUIT_GYRO_ACCELEROMETER_LSM6DS33_H
#define INC_3_INTER_INTEGRATED_CIRCUIT_GYRO_ACCELEROMETER_LSM6DS33_H


class gyro_accelerometer_LSM6DS33 {

};


#endif //INC_3_INTER_INTEGRATED_CIRCUIT_GYRO_ACCELEROMETER_LSM6DS33_H
